-- Final OLAP analytical sessions. Generated by analysis/sessions.py --export.
-- Shared query definitions: dashboard/queries.py. No stored aggregates.
-- All citation measures are cumulative snapshots at extraction, not citations received in publication year.
-- Full counts participation; fractional uses original leaf weights. Filters use independent EXISTS.
-- Results describe the reproducible year-stratified OpenAlex sample, not the complete population; inspect the raw manifest.
BEGIN TRANSACTION READ ONLY;

-- SESSION 1: Research Growth
-- Question: Does observed publication output show acceleration after 2022?
-- Navigation: Roll up to Year; adjacent-period growth, no growth from zero base
WITH filtered_publications AS (
    SELECT
        publication.publication_key,
        publication.source_key,
        publication.publication_type,
        publication.language,
        publication.is_open_access,
        publication.publication_count,
        publication.citation_count,
        date_dim.calendar_year,
        date_dim.full_date, date_dim.quarter_number, date_dim.month_number
    FROM dw.fact_publication publication
    LEFT JOIN dw.dim_date date_dim
        ON date_dim.date_key = publication.date_key
    LEFT JOIN dw.dim_source source
        ON source.source_key = publication.source_key
    WHERE date_dim.calendar_year >= 2018 AND
            date_dim.calendar_year <= 2025
)
, bounds AS (
            SELECT min(full_date) AS first_date, max(full_date) AS last_date
            FROM filtered_publications
        ), periods AS (
            SELECT generate_series(date_trunc('year', first_date),
                                   date_trunc('year', last_date), interval '1 year')::date AS period
            FROM bounds
        ), counts AS (
            SELECT date_trunc('year', full_date)::date AS period,
                   sum(publication_count) AS publications
            FROM filtered_publications GROUP BY 1
        ), series AS (
            SELECT period, coalesce(publications, 0) AS publications
            FROM periods LEFT JOIN counts USING (period)
        )
        SELECT period, publications,
               100.0 * (publications - lag(publications) OVER (ORDER BY period))
                   / nullif(lag(publications) OVER (ORDER BY period), 0) AS period_growth_pct
        FROM series ORDER BY period;
-- Navigation: Dice 2022–2025 and drill to Quarter
WITH filtered_publications AS (
    SELECT
        publication.publication_key,
        publication.source_key,
        publication.publication_type,
        publication.language,
        publication.is_open_access,
        publication.publication_count,
        publication.citation_count,
        date_dim.calendar_year,
        date_dim.full_date, date_dim.quarter_number, date_dim.month_number
    FROM dw.fact_publication publication
    LEFT JOIN dw.dim_date date_dim
        ON date_dim.date_key = publication.date_key
    LEFT JOIN dw.dim_source source
        ON source.source_key = publication.source_key
    WHERE date_dim.calendar_year >= 2022 AND
            date_dim.calendar_year <= 2025
)
, bounds AS (
            SELECT min(full_date) AS first_date, max(full_date) AS last_date
            FROM filtered_publications
        ), periods AS (
            SELECT generate_series(date_trunc('quarter', first_date),
                                   date_trunc('quarter', last_date), interval '3 months')::date AS period
            FROM bounds
        ), counts AS (
            SELECT date_trunc('quarter', full_date)::date AS period,
                   sum(publication_count) AS publications
            FROM filtered_publications GROUP BY 1
        ), series AS (
            SELECT period, coalesce(publications, 0) AS publications
            FROM periods LEFT JOIN counts USING (period)
        )
        SELECT period, publications,
               100.0 * (publications - lag(publications) OVER (ORDER BY period))
                   / nullif(lag(publications) OVER (ORDER BY period), 0) AS period_growth_pct
        FROM series ORDER BY period;
-- Navigation: Drill to Month in selected final year
WITH filtered_publications AS (
    SELECT
        publication.publication_key,
        publication.source_key,
        publication.publication_type,
        publication.language,
        publication.is_open_access,
        publication.publication_count,
        publication.citation_count,
        date_dim.calendar_year,
        date_dim.full_date, date_dim.quarter_number, date_dim.month_number
    FROM dw.fact_publication publication
    LEFT JOIN dw.dim_date date_dim
        ON date_dim.date_key = publication.date_key
    LEFT JOIN dw.dim_source source
        ON source.source_key = publication.source_key
    WHERE date_dim.calendar_year >= 2025 AND
            date_dim.calendar_year <= 2025
)
, bounds AS (
            SELECT min(full_date) AS first_date, max(full_date) AS last_date
            FROM filtered_publications
        ), periods AS (
            SELECT generate_series(date_trunc('month', first_date),
                                   date_trunc('month', last_date), interval '1 month')::date AS period
            FROM bounds
        ), counts AS (
            SELECT date_trunc('month', full_date)::date AS period,
                   sum(publication_count) AS publications
            FROM filtered_publications GROUP BY 1
        ), series AS (
            SELECT period, coalesce(publications, 0) AS publications
            FROM periods LEFT JOIN counts USING (period)
        )
        SELECT period, publications,
               100.0 * (publications - lag(publications) OVER (ORDER BY period))
                   / nullif(lag(publications) OVER (ORDER BY period), 0) AS period_growth_pct
        FROM series ORDER BY period;
-- Navigation: Slice by publication type and year
WITH filtered_publications AS (
    SELECT
        publication.publication_key,
        publication.source_key,
        publication.publication_type,
        publication.language,
        publication.is_open_access,
        publication.publication_count,
        publication.citation_count,
        date_dim.calendar_year,
        date_dim.full_date, date_dim.quarter_number, date_dim.month_number
    FROM dw.fact_publication publication
    LEFT JOIN dw.dim_date date_dim
        ON date_dim.date_key = publication.date_key
    LEFT JOIN dw.dim_source source
        ON source.source_key = publication.source_key
    WHERE date_dim.calendar_year >= 2018 AND
            date_dim.calendar_year <= 2025
)
SELECT calendar_year,
               coalesce(publication_type, 'Missing / unavailable') AS publication_type,
               sum(publication_count)::numeric AS publications
        FROM filtered_publications
        GROUP BY calendar_year, coalesce(publication_type, 'Missing / unavailable')
        ORDER BY calendar_year, publication_type;
-- Navigation: Slice by Open Access boolean and year
WITH filtered_publications AS (
    SELECT
        publication.publication_key,
        publication.source_key,
        publication.publication_type,
        publication.language,
        publication.is_open_access,
        publication.publication_count,
        publication.citation_count,
        date_dim.calendar_year,
        date_dim.full_date, date_dim.quarter_number, date_dim.month_number
    FROM dw.fact_publication publication
    LEFT JOIN dw.dim_date date_dim
        ON date_dim.date_key = publication.date_key
    LEFT JOIN dw.dim_source source
        ON source.source_key = publication.source_key
    WHERE date_dim.calendar_year >= 2018 AND
            date_dim.calendar_year <= 2025
)
SELECT calendar_year,
               CASE WHEN is_open_access THEN 'Open Access'
                    WHEN is_open_access IS FALSE THEN 'Not Open Access'
                    ELSE 'Missing / unavailable' END AS open_access,
               sum(publication_count)::numeric AS publications
        FROM filtered_publications
        GROUP BY calendar_year, is_open_access
        ORDER BY calendar_year, is_open_access DESC NULLS LAST;

-- SESSION 2: Geographic & Normalized Leadership
-- Question: Does leadership change after accounting for country size and economic capacity?
-- Navigation: Full participation: one publication per participating country
WITH filtered_publications AS (
    SELECT
        publication.publication_key,
        publication.source_key,
        publication.publication_type,
        publication.language,
        publication.is_open_access,
        publication.publication_count,
        publication.citation_count,
        date_dim.calendar_year,
        date_dim.full_date, date_dim.quarter_number, date_dim.month_number
    FROM dw.fact_publication publication
    LEFT JOIN dw.dim_date date_dim
        ON date_dim.date_key = publication.date_key
    LEFT JOIN dw.dim_source source
        ON source.source_key = publication.source_key
    WHERE date_dim.calendar_year >= 2018 AND
            date_dim.calendar_year <= 2025
)
        SELECT country.country_code_iso2,
               country.country_code_iso3,
               coalesce(country.country_name, country.country_code_iso2) AS country_name,
               country.region_name,
               country.income_level_name,
               country.has_world_bank_data,
               sum(selected.publication_count)::numeric AS publications
        FROM filtered_publications selected
        JOIN dw.bridge_publication_country bridge
          ON bridge.publication_key = selected.publication_key
        JOIN dw.dim_country country ON country.country_key = bridge.country_key
        WHERE TRUE
        GROUP BY country.country_key, country.country_code_iso2,
                 country.country_code_iso3, country.country_name,
                 country.region_name, country.income_level_name,
                 country.has_world_bank_data
        ORDER BY publications DESC NULLS LAST, country_name
        LIMIT 30;
-- Navigation: Fractional attribution: original country weights
WITH filtered_publications AS (
    SELECT
        publication.publication_key,
        publication.source_key,
        publication.publication_type,
        publication.language,
        publication.is_open_access,
        publication.publication_count,
        publication.citation_count,
        date_dim.calendar_year,
        date_dim.full_date, date_dim.quarter_number, date_dim.month_number
    FROM dw.fact_publication publication
    LEFT JOIN dw.dim_date date_dim
        ON date_dim.date_key = publication.date_key
    LEFT JOIN dw.dim_source source
        ON source.source_key = publication.source_key
    WHERE date_dim.calendar_year >= 2018 AND
            date_dim.calendar_year <= 2025
)
        SELECT country.country_code_iso2,
               country.country_code_iso3,
               coalesce(country.country_name, country.country_code_iso2) AS country_name,
               country.region_name,
               country.income_level_name,
               country.has_world_bank_data,
               sum(selected.publication_count * bridge.fractional_weight)::numeric AS publications
        FROM filtered_publications selected
        JOIN dw.bridge_publication_country bridge
          ON bridge.publication_key = selected.publication_key
        JOIN dw.dim_country country ON country.country_key = bridge.country_key
        WHERE TRUE
        GROUP BY country.country_key, country.country_code_iso2,
                 country.country_code_iso3, country.country_name,
                 country.region_name, country.income_level_name,
                 country.has_world_bank_data
        ORDER BY publications DESC NULLS LAST, country_name
        LIMIT 30;
-- Navigation: Drill to Country x Year, then across WDI; NULL denominators have no rank
WITH country_year AS (
        WITH filtered_publications AS (
    SELECT
        publication.publication_key,
        publication.source_key,
        publication.publication_type,
        publication.language,
        publication.is_open_access,
        publication.publication_count,
        publication.citation_count,
        date_dim.calendar_year,
        date_dim.full_date, date_dim.quarter_number, date_dim.month_number
    FROM dw.fact_publication publication
    LEFT JOIN dw.dim_date date_dim
        ON date_dim.date_key = publication.date_key
    LEFT JOIN dw.dim_source source
        ON source.source_key = publication.source_key
    WHERE date_dim.calendar_year >= 2018 AND
            date_dim.calendar_year <= 2025
),
        publication_country_year AS (
            SELECT country.country_key,
                   country.country_code_iso2,
                   country.country_code_iso3,
                   coalesce(country.country_name, country.country_code_iso2) AS country_name,
                   country.region_name,
                   country.income_level_name,
                   country.has_world_bank_data,
                   selected.calendar_year,
                   sum(selected.publication_count) AS full_publications,
                   sum(selected.publication_count * bridge.fractional_weight)::numeric
                       AS fractional_publications
            FROM filtered_publications selected
            JOIN dw.bridge_publication_country bridge
              ON bridge.publication_key = selected.publication_key
            JOIN dw.dim_country country ON country.country_key = bridge.country_key
            WHERE TRUE
            GROUP BY country.country_key, country.country_code_iso2,
                     country.country_code_iso3, country.country_name,
                     country.region_name, country.income_level_name,
                     country.has_world_bank_data, selected.calendar_year
        )
        SELECT publication.country_code_iso2,
               publication.country_code_iso3,
               publication.country_name,
               publication.region_name,
               publication.income_level_name,
               publication.has_world_bank_data,
               publication.calendar_year,
               publication.fractional_publications,
               indicator.population,
               indicator.gdp_current_usd,
               indicator.gdp_per_capita_current_usd,
               indicator.internet_users_pct,
               indicator.rd_expenditure_pct_gdp,
               CASE WHEN indicator.population IS NULL OR indicator.population = 0
                    THEN NULL
                    ELSE publication.fractional_publications * 1000000::numeric
                         / indicator.population
               END AS publications_per_million,
               CASE WHEN indicator.gdp_current_usd IS NULL OR indicator.gdp_current_usd = 0
                    THEN NULL
                    ELSE publication.fractional_publications * 1000000000::numeric
                         / indicator.gdp_current_usd
               END AS publications_per_billion_gdp,
               publication.full_publications
        FROM publication_country_year publication
        LEFT JOIN dw.fact_country_year indicator
          ON indicator.country_key = publication.country_key
         AND indicator.year = publication.calendar_year
        ORDER BY publication.calendar_year, publication.country_name
        ), ranked AS (
            SELECT *, rank() OVER (PARTITION BY calendar_year ORDER BY fractional_publications DESC) AS absolute_rank,
                   CASE WHEN publications_per_million IS NOT NULL THEN
                       rank() OVER (PARTITION BY calendar_year ORDER BY publications_per_million DESC NULLS LAST)
                   END AS per_million_rank,
                   CASE WHEN publications_per_billion_gdp IS NOT NULL THEN
                       rank() OVER (PARTITION BY calendar_year ORDER BY publications_per_billion_gdp DESC NULLS LAST)
                   END AS per_gdp_rank
            FROM country_year
        )
        SELECT *, absolute_rank - per_million_rank AS population_rank_shift,
                  absolute_rank - per_gdp_rank AS gdp_rank_shift
        FROM ranked ORDER BY calendar_year, absolute_rank, country_code_iso2;

-- SESSION 3: Income-Level Research Gap
-- Question: How does country output and normalized intensity vary across income levels over time?
-- Navigation: Country to Income Level x Year; full, fractional and matched-denominator ratios
WITH filtered_publications AS (
    SELECT
        publication.publication_key,
        publication.source_key,
        publication.publication_type,
        publication.language,
        publication.is_open_access,
        publication.publication_count,
        publication.citation_count,
        date_dim.calendar_year,
        date_dim.full_date, date_dim.quarter_number, date_dim.month_number
    FROM dw.fact_publication publication
    LEFT JOIN dw.dim_date date_dim
        ON date_dim.date_key = publication.date_key
    LEFT JOIN dw.dim_source source
        ON source.source_key = publication.source_key
    WHERE date_dim.calendar_year >= 2018 AND
            date_dim.calendar_year <= 2025
), year_coordinates AS (
            SELECT DISTINCT year AS calendar_year FROM dw.fact_country_year
        ), country_output AS (
            SELECT country_key, calendar_year, sum(fractional_weight) AS fractional_publications
            FROM filtered_publications JOIN dw.bridge_publication_country USING (publication_key)
            GROUP BY country_key, calendar_year
        ), country_year AS (
            SELECT country.country_key, country.income_level_name AS member,
                   year_coordinate.calendar_year, coalesce(output.fractional_publications, 0) AS fractional_publications,
                   indicator.population, indicator.gdp_current_usd
            FROM dw.dim_country country CROSS JOIN year_coordinates year_coordinate
            LEFT JOIN country_output output ON output.country_key = country.country_key
                AND output.calendar_year = year_coordinate.calendar_year
            LEFT JOIN dw.fact_country_year indicator ON indicator.country_key = country.country_key
                AND indicator.year = year_coordinate.calendar_year
            WHERE year_coordinate.calendar_year >= 2018 AND year_coordinate.calendar_year <= 2025
        ), group_publication AS (
            SELECT country.income_level_name AS member, selected.calendar_year, selected.publication_key
            FROM filtered_publications selected
            JOIN dw.bridge_publication_country bridge USING (publication_key)
            JOIN dw.dim_country country USING (country_key)
            WHERE TRUE
            GROUP BY country.income_level_name, selected.calendar_year, selected.publication_key
        ), full_output AS (
            SELECT member, calendar_year, count(*) AS full_publications
            FROM group_publication GROUP BY member, calendar_year
        )
        SELECT coalesce(c.member, 'Missing / unavailable') AS member, c.calendar_year,
               coalesce(f.full_publications, 0) AS full_publications,
               sum(c.fractional_publications) AS fractional_publications,
               sum(c.population) AS population, sum(c.gdp_current_usd) AS gdp_current_usd,
               1000000::numeric * sum(c.fractional_publications) FILTER (WHERE c.population > 0)
                 / nullif(sum(c.population) FILTER (WHERE c.population > 0), 0) AS publications_per_million,
               1000000000::numeric * sum(c.fractional_publications) FILTER (WHERE c.gdp_current_usd > 0)
                 / nullif(sum(c.gdp_current_usd) FILTER (WHERE c.gdp_current_usd > 0), 0) AS publications_per_billion_gdp,
               count(*) AS countries,
               count(*) FILTER (WHERE c.population > 0) AS population_countries,
               count(*) FILTER (WHERE c.gdp_current_usd > 0) AS gdp_countries
        FROM country_year c LEFT JOIN full_output f
          ON f.member IS NOT DISTINCT FROM c.member AND f.calendar_year = c.calendar_year
        GROUP BY c.member, c.calendar_year, f.full_publications
        ORDER BY c.calendar_year, fractional_publications DESC, member;

-- SESSION 4: Topic Specialization & Thematic Evolution
-- Question: Which source-native topics characterize the selected corpus over time?
-- Navigation: Roll up Topic to Domain: full appearance, once per publication and Domain
WITH filtered_publications AS (
    SELECT
        publication.publication_key,
        publication.source_key,
        publication.publication_type,
        publication.language,
        publication.is_open_access,
        publication.publication_count,
        publication.citation_count,
        date_dim.calendar_year,
        date_dim.full_date, date_dim.quarter_number, date_dim.month_number
    FROM dw.fact_publication publication
    LEFT JOIN dw.dim_date date_dim
        ON date_dim.date_key = publication.date_key
    LEFT JOIN dw.dim_source source
        ON source.source_key = publication.source_key
    WHERE date_dim.calendar_year >= 2018 AND
            date_dim.calendar_year <= 2025
), publication_member AS (
            SELECT selected.publication_key, selected.calendar_year,
                   coalesce(topic.domain_id, '__MISSING__') AS member_id,
                   coalesce(topic.domain_name, topic.domain_id, 'Missing / unavailable') AS member_name,
                   1::numeric AS attributed_publications
            FROM filtered_publications selected
            JOIN dw.bridge_publication_topic bridge USING (publication_key)
            JOIN dw.dim_topic topic USING (topic_key)
            WHERE TRUE
            GROUP BY selected.publication_key, selected.calendar_year, topic.domain_id, topic.domain_name
        ), member_year AS (
            SELECT member_id, member_name, sum(attributed_publications) AS publications
            FROM publication_member GROUP BY member_id, member_name
        ), leaders AS (
            SELECT member_id FROM member_year GROUP BY member_id
            ORDER BY sum(publications) DESC, member_id LIMIT 30
        )
        SELECT member_year.member_id, member_year.member_name, member_year.publications
        FROM member_year JOIN leaders USING (member_id)
        ORDER BY  publications DESC, member_name;
-- Navigation: Drill to Subfield x Year: full appearance
WITH filtered_publications AS (
    SELECT
        publication.publication_key,
        publication.source_key,
        publication.publication_type,
        publication.language,
        publication.is_open_access,
        publication.publication_count,
        publication.citation_count,
        date_dim.calendar_year,
        date_dim.full_date, date_dim.quarter_number, date_dim.month_number
    FROM dw.fact_publication publication
    LEFT JOIN dw.dim_date date_dim
        ON date_dim.date_key = publication.date_key
    LEFT JOIN dw.dim_source source
        ON source.source_key = publication.source_key
    WHERE date_dim.calendar_year >= 2018 AND
            date_dim.calendar_year <= 2025
), publication_member AS (
            SELECT selected.publication_key, selected.calendar_year,
                   coalesce(topic.subfield_id, '__MISSING__') AS member_id,
                   coalesce(topic.subfield_name, topic.subfield_id, 'Missing / unavailable') AS member_name,
                   1::numeric AS attributed_publications
            FROM filtered_publications selected
            JOIN dw.bridge_publication_topic bridge USING (publication_key)
            JOIN dw.dim_topic topic USING (topic_key)
            WHERE TRUE
            GROUP BY selected.publication_key, selected.calendar_year, topic.subfield_id, topic.subfield_name
        ), member_year AS (
            SELECT member_id, member_name, calendar_year, sum(attributed_publications) AS publications
            FROM publication_member GROUP BY member_id, member_name, calendar_year
        ), leaders AS (
            SELECT member_id FROM member_year GROUP BY member_id
            ORDER BY sum(publications) DESC, member_id LIMIT 8
        )
        SELECT member_year.member_id, member_year.member_name, member_year.calendar_year, member_year.publications
        FROM member_year JOIN leaders USING (member_id)
        ORDER BY calendar_year, publications DESC, member_name;
-- Navigation: Drill to Topic and change measure to fractional topic attribution
WITH filtered_publications AS (
    SELECT
        publication.publication_key,
        publication.source_key,
        publication.publication_type,
        publication.language,
        publication.is_open_access,
        publication.publication_count,
        publication.citation_count,
        date_dim.calendar_year,
        date_dim.full_date, date_dim.quarter_number, date_dim.month_number
    FROM dw.fact_publication publication
    LEFT JOIN dw.dim_date date_dim
        ON date_dim.date_key = publication.date_key
    LEFT JOIN dw.dim_source source
        ON source.source_key = publication.source_key
    WHERE date_dim.calendar_year >= 2018 AND
            date_dim.calendar_year <= 2025
), publication_member AS (
            SELECT selected.publication_key, selected.calendar_year,
                   coalesce(topic.openalex_topic_id, '__MISSING__') AS member_id,
                   coalesce(topic.topic_name, topic.openalex_topic_id, 'Missing / unavailable') AS member_name,
                   sum(bridge.fractional_weight) AS attributed_publications
            FROM filtered_publications selected
            JOIN dw.bridge_publication_topic bridge USING (publication_key)
            JOIN dw.dim_topic topic USING (topic_key)
            WHERE TRUE
            GROUP BY selected.publication_key, selected.calendar_year, topic.openalex_topic_id, topic.topic_name
        ), member_year AS (
            SELECT member_id, member_name, sum(attributed_publications) AS publications
            FROM publication_member GROUP BY member_id, member_name
        ), leaders AS (
            SELECT member_id FROM member_year GROUP BY member_id
            ORDER BY sum(publications) DESC, member_id LIMIT 30
        )
        SELECT member_year.member_id, member_year.member_name, member_year.publications
        FROM member_year JOIN leaders USING (member_id)
        ORDER BY  publications DESC, member_name;

-- SESSION 5: Wealth vs AI Research Intensity
-- Question: Is GDP per capita associated with fractional publications per million?
-- Navigation: Slice selected year; Region/Income Level are alternative country attributes
WITH filtered_publications AS (
    SELECT
        publication.publication_key,
        publication.source_key,
        publication.publication_type,
        publication.language,
        publication.is_open_access,
        publication.publication_count,
        publication.citation_count,
        date_dim.calendar_year,
        date_dim.full_date, date_dim.quarter_number, date_dim.month_number
    FROM dw.fact_publication publication
    LEFT JOIN dw.dim_date date_dim
        ON date_dim.date_key = publication.date_key
    LEFT JOIN dw.dim_source source
        ON source.source_key = publication.source_key
    WHERE date_dim.calendar_year >= 2025 AND
            date_dim.calendar_year <= 2025
),
        publication_country_year AS (
            SELECT country.country_key,
                   country.country_code_iso2,
                   country.country_code_iso3,
                   coalesce(country.country_name, country.country_code_iso2) AS country_name,
                   country.region_name,
                   country.income_level_name,
                   country.has_world_bank_data,
                   selected.calendar_year,
                   sum(selected.publication_count) AS full_publications,
                   sum(selected.publication_count * bridge.fractional_weight)::numeric
                       AS fractional_publications
            FROM filtered_publications selected
            JOIN dw.bridge_publication_country bridge
              ON bridge.publication_key = selected.publication_key
            JOIN dw.dim_country country ON country.country_key = bridge.country_key
            WHERE TRUE
            GROUP BY country.country_key, country.country_code_iso2,
                     country.country_code_iso3, country.country_name,
                     country.region_name, country.income_level_name,
                     country.has_world_bank_data, selected.calendar_year
        )
        SELECT publication.country_code_iso2,
               publication.country_code_iso3,
               publication.country_name,
               publication.region_name,
               publication.income_level_name,
               publication.has_world_bank_data,
               publication.calendar_year,
               publication.fractional_publications,
               indicator.population,
               indicator.gdp_current_usd,
               indicator.gdp_per_capita_current_usd,
               indicator.internet_users_pct,
               indicator.rd_expenditure_pct_gdp,
               CASE WHEN indicator.population IS NULL OR indicator.population = 0
                    THEN NULL
                    ELSE publication.fractional_publications * 1000000::numeric
                         / indicator.population
               END AS publications_per_million,
               CASE WHEN indicator.gdp_current_usd IS NULL OR indicator.gdp_current_usd = 0
                    THEN NULL
                    ELSE publication.fractional_publications * 1000000000::numeric
                         / indicator.gdp_current_usd
               END AS publications_per_billion_gdp,
               publication.full_publications
        FROM publication_country_year publication
        LEFT JOIN dw.fact_country_year indicator
          ON indicator.country_key = publication.country_key
         AND indicator.year = publication.calendar_year
        ORDER BY publication.calendar_year, publication.country_name;

-- SESSION 6: Institutional Leadership
-- Question: Which institution types and institutions participate in the corpus?
-- Navigation: Roll up Institution Type: full participation once per publication/type
SELECT member_name AS institution_type, publications FROM (
        WITH filtered_publications AS (
    SELECT
        publication.publication_key,
        publication.source_key,
        publication.publication_type,
        publication.language,
        publication.is_open_access,
        publication.publication_count,
        publication.citation_count,
        date_dim.calendar_year,
        date_dim.full_date, date_dim.quarter_number, date_dim.month_number
    FROM dw.fact_publication publication
    LEFT JOIN dw.dim_date date_dim
        ON date_dim.date_key = publication.date_key
    LEFT JOIN dw.dim_source source
        ON source.source_key = publication.source_key
    WHERE date_dim.calendar_year >= 2018 AND
            date_dim.calendar_year <= 2025
), publication_member AS (
            SELECT selected.publication_key, selected.calendar_year,
                   coalesce(institution.institution_type, '__MISSING__') AS member_id,
                   coalesce(institution.institution_type, institution.institution_type, 'Missing / unavailable') AS member_name,
                   1::numeric AS attributed_publications
            FROM filtered_publications selected
            JOIN dw.bridge_publication_institution bridge USING (publication_key)
            JOIN dw.dim_institution institution USING (institution_key)
            WHERE TRUE
            GROUP BY selected.publication_key, selected.calendar_year, institution.institution_type, institution.institution_type
        ), member_year AS (
            SELECT member_id, member_name, sum(attributed_publications) AS publications
            FROM publication_member GROUP BY member_id, member_name
        ), leaders AS (
            SELECT member_id FROM member_year GROUP BY member_id
            ORDER BY sum(publications) DESC, member_id LIMIT 50
        )
        SELECT member_year.member_id, member_year.member_name, member_year.publications
        FROM member_year JOIN leaders USING (member_id)
        ORDER BY  publications DESC, member_name
    ) result;
-- Navigation: Drill to Institution: full participation
WITH filtered_publications AS (
    SELECT
        publication.publication_key,
        publication.source_key,
        publication.publication_type,
        publication.language,
        publication.is_open_access,
        publication.publication_count,
        publication.citation_count,
        date_dim.calendar_year,
        date_dim.full_date, date_dim.quarter_number, date_dim.month_number
    FROM dw.fact_publication publication
    LEFT JOIN dw.dim_date date_dim
        ON date_dim.date_key = publication.date_key
    LEFT JOIN dw.dim_source source
        ON source.source_key = publication.source_key
    WHERE date_dim.calendar_year >= 2018 AND
            date_dim.calendar_year <= 2025
)
        SELECT institution.openalex_institution_id AS institution_id,
               coalesce(institution.institution_name,
                        institution.openalex_institution_id) AS institution_name,
               institution.institution_type,
               institution.country_code_iso2,
               sum(selected.publication_count)::numeric AS publications
        FROM filtered_publications selected
        JOIN dw.bridge_publication_institution bridge
          ON bridge.publication_key = selected.publication_key
        JOIN dw.dim_institution institution
          ON institution.institution_key = bridge.institution_key
        WHERE TRUE
        GROUP BY institution.institution_key, institution.openalex_institution_id,
                 institution.institution_name, institution.institution_type,
                 institution.country_code_iso2
        ORDER BY publications DESC NULLS LAST, institution_name
        LIMIT 30;
-- Navigation: Change measure to fractional institution attribution
WITH filtered_publications AS (
    SELECT
        publication.publication_key,
        publication.source_key,
        publication.publication_type,
        publication.language,
        publication.is_open_access,
        publication.publication_count,
        publication.citation_count,
        date_dim.calendar_year,
        date_dim.full_date, date_dim.quarter_number, date_dim.month_number
    FROM dw.fact_publication publication
    LEFT JOIN dw.dim_date date_dim
        ON date_dim.date_key = publication.date_key
    LEFT JOIN dw.dim_source source
        ON source.source_key = publication.source_key
    WHERE date_dim.calendar_year >= 2018 AND
            date_dim.calendar_year <= 2025
)
        SELECT institution.openalex_institution_id AS institution_id,
               coalesce(institution.institution_name,
                        institution.openalex_institution_id) AS institution_name,
               institution.institution_type,
               institution.country_code_iso2,
               sum(selected.publication_count * bridge.fractional_weight)::numeric AS publications
        FROM filtered_publications selected
        JOIN dw.bridge_publication_institution bridge
          ON bridge.publication_key = selected.publication_key
        JOIN dw.dim_institution institution
          ON institution.institution_key = bridge.institution_key
        WHERE TRUE
        GROUP BY institution.institution_key, institution.openalex_institution_id,
                 institution.institution_name, institution.institution_type,
                 institution.country_code_iso2
        ORDER BY publications DESC NULLS LAST, institution_name
        LIMIT 30;
COMMIT;
